name: phpunit

on:
  push:
    branches: [master]
  pull_request:

jobs:
  tests:
    runs-on: docker
    container:
      image: php:8.4-cli
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run PHPUnit
        run: |
          php -v
          curl -fsSL -o /tmp/phpunit.phar https://phar.phpunit.de/phpunit-11.phar
          php /tmp/phpunit.phar --configuration phpunit.xml
